title: "Zehan (Leo) Li"
description: "AI & Biomedical Informatics for Mental Health"
baseurl: ""
url: "https://leoliaugust1230.github.io"
theme: journal # Switch to Journal theme for a more elegant layout
markdown: kramdown

# Navigation Menu
header_pages:
  - index.md
  - about.md
  - research.md
  - projects.md
  - presentations.md
  - life.md
  - contact.md

# Sidebar Image (for Journal theme)
sidebar-img: "assets/sidebar.jpg"

# Plugins
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-paginate

# Social Links
social:
  github: "https://github.com/leoliaugust1230/"
  scholar: "https://scholar.google.com/citations?hl=en&user=Aa3mKPQAAAAJ&view_op=list_works"
  email: "zehan.li@uth.tmc.edu"

# SEO Settings
author: "Zehan (Leo) Li"

# Pagination (for blogs or articles)
paginate: 5
paginate_path: "/page:num/"
